### ISSUE TITLE
[BUG] Launcher gets stuck on updating game even if all the files are installed.

### ISSUE THREAD

**Issue by Mjrlun** [garretreichenbach/New-StarMade-Launcher#2]
OS: Windows 11
Java Version: JRE 18 (the embedded one)
Launcher install directory: Custom
Game Version: 0.300.101 (Pre-Release)
Game Install directory: Custom
Java installation directory: Custom
Java class path directory: Custom (relative to the installation directory)
_The launcher was opened via the command line seen as the launcher executable crashes after 3 seconds_

When updating the game, the launcher gets stuck with no information added to the console, after it has identified and installed all necessary components.

Extra context for the log file:
I had already updated the game before when it hang on this exact same issue (but instead downloading/installing things). I restarted the launcher and the error persisted. All of the game's files that were supposed to be downloaded do exist within the game installation directory.
[Launcher console output](https://github.com/garretreichenbach/New-StarMade-Launcher/files/13621467/Starmade.launcher.console.output.txt)

Launcher GUI during the issue:
![image](https://github.com/garretreichenbach/New-StarMade-Launcher/assets/84252662/70bc4c7a-3750-4b6b-8ec7-48a591588525)

**Comment by garretreichenbach** [comment]
Fixed in v3.0.2
